USE ROLE SYSADMIN;

CREATE WAREHOUSE CH2_WH WITH WAREHOUSE_SIZE = MEDIUM 
  AUTO_SUSPEND = 300 
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

USE ROLE SYSADMIN;
ALTER WAREHOUSE CH2_WH 
  SET WAREHOUSE_SIZE = LARGE; 


  USE ROLE SYYSADMIN;
CREATE OR REPLACE WAREHOUSE ACCOUNTING_WH WITH WAREHOUSE_SIZE =  MEDIUM
    MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 6
    SCALING_POLICY = STANDARD;

ALTER SESSION SET USE_CACHED_RESULT = FALSE;

USE ROLE SYSADMIN;
ALTER SESSION SET USE_CACHED_RESULT = TRUE;
DROP WAREHOUSE CH2_WH;
DROP WAREHOUSE ACCOUNTING_WH;