USE ROLE SYSADMIN;
USE WAREHOUSE COMPUTE_WH;
CREATE OR REPLACE DATABASE DEMO4_DB;
CREATE OR REPLACE SCHEMA  SUBQUERIES;

CREATE OR REPLACE TABLE DEMO04_DB.SUBQUERIES.DERIVED(ID integer, AMT integer, Total integer);
INSERT INTO DEMO04_DB.SUBQUERIES.DERIVED(ID, AMT, Total)
VALUES (1,1000,4000),(2,2000,3500),(3,3000, 9900),(4,4000,3000),
 (5,5000,3700),(6,6000,2222);
SELECT * FROM DEMO4_DB.SUBQUERIES.DERIVED; 


CREATE OR REPLACE TABLE DEMO4_DB.SUBQUERIES.TABLE2
 (ID integer, AMT integer, Total integer);
INSERT INTO TABLE2 (ID, AMT, Total)
VALUES (1,1000,8300),(2,1001,1900),(3,3000,4400),(4,1010,3535),
 (5,1200,3232),(6,1000,2222);
SELECT * FROM DEMO4_DB.SUBQUERIES.TABLE2;


--UNCORELATED SUBQUERIES
SELECT ID, AMT 
FROM DEMO4_DB.SUBQUERIES.DERIVED
WHERE AMT = (SELECT MAX(AMT) FROM DEMO4_DB.SUBQUERIES.DERIVED);

--CORRELATED SUBQUERIES
SELECT ID, AMT
FROM DEMO4_DB.SUBQUERIES.DERIVED
WHERE AMT = (SELECT MAX(AMT) FROM DEMO4_DB.SUBQUERIES.TABLE2  WHERE ID = ID);


SELECT ID, AMT
FROM DEMO4_DB.SUBQUERIES.DERIVED
WHERE AMT > (SELECT avg(AMT) FROM DEMO4_DB.SUBQUERIES.TABLE2  WHERE ID = ID);

-- DERIVED COLUMNS
SELECT ID, AMT, AMT * 10 AS AMT1, AMT1 + 20 AS AMT2
FROM DEMO4_DB.SUBQUERIES.DERIVED;


SELECT SUB.ID, SUB.AMT, SUB.AMT1 + 20 AS AMT2
FROM
(SELECT ID, AMT, AMT * 10 AS AMT1
FROM DEMO4_DB.SUBQUERIES.DERIVED) AS  SUB;


--CTE
WITH CTE1 AS (
    SELECT ID, AMT, AMT * 10 AS AMT2
    FROM DEMO4_DB.SUBQUERIES.DERIVED
)
SELECT A.ID, A.AMT, B.AMT2 + 20 AS AMT2
FROM DEMO4_DB.SUBQUERIES.DERIVED A
JOIN CTE1 B ON A.ID = B.ID; 


-- MULTI ROW INSERTS
USE ROLE SYSADMIN;
CREATE OR REPLACE SCHEMA DEMO4_DB.TEST;
CREATE OR REPLACE TABLE DEMO4_DB.TEST.TEST1 (ID integer, DEPT Varchar);
INSERT INTO TEST1 (ID, DEPT)
VALUES (1,'one');
SELECT * FROM DEMO4_DB.TEST.TEST1;


USE ROLE SYSADMIN;
CREATE OR REPLACE SCHEMA DEMO4_DB.TEST;
CREATE OR REPLACE TABLE DEMO4_DB.TEST.TEST1 (ID integer, DEPT Varchar);
INSERT INTO TEST1 (ID, DEPT)
VALUES (1,1);
SELECT * FROM DEMO4_DB.TEST.TEST1;

//Error is expected
USE ROLE SYSADMIN;

CREATE OR REPLACE SCHEMA DEMO4_DB.TEST;
CREATE OR REPLACE TABLE DEMO4_DB.TEST.TEST1 (ID integer, DEPT Varchar);
INSERT INTO TEST1 (ID, DEPT)
VALUES (1,'one'), (2,2);
SELECT * FROM DEMO4_DB.TEST.TEST1;


USE ROLE SYSADMIN;
CREATE OR REPLACE SCHEMA DEMO4_DB.TEST;
CREATE OR REPLACE TABLE DEMO4_DB.TEST.TEST1 (ID integer, DEPT Varchar);
INSERT INTO TEST1 (ID, DEPT)
VALUES (1,'one'), (2,'two');
SELECT * FROM DEMO4_DB.TEST.TEST1;

// Page 124 - Now insert two numerical values
USE ROLE SYSADMIN;
CREATE OR REPLACE SCHEMA DEMO4_DB.TEST;
CREATE OR REPLACE TABLE DEMO4_DB.TEST.TEST1 (ID integer, DEPT Varchar);
INSERT INTO TEST1 (ID, DEPT)
VALUES (1,1), (2,2);
SELECT * FROM DEMO4_DB.TEST.TEST1;

// Page 124 - Continue to add another value
INSERT INTO TEST1 (ID, DEPT)
VALUES (5, 'five');
SELECT * FROM DEMO4_DB.TEST.TEST1;


USE ROLE SYSADMIN;
USE SCHEMA DEMO4_DB.DATATYPES;

CREATE OR REPLACE TABLE TEXTSTRING(
    VARCHAR VARCHAR,
    V100 VARCHAR(100),
    CHAR CHAR,
    C100 CHAR(100),
    STRING STRING,
    S100 STRING(100),
    TEXT TEXT,
    T100 TEXT(100));

DESC TABLE TEXTSTRING;